main: rush.Main
version: 1.10
name: System
load: POSTWORLD
author: RUSH
softdepend: [Legendchat, mcMMO, MassiveCore, Factions, Vault]

permissions:
  system.alerta:
    description: Permissão para enviar um alerta no servidor.
    default: op
  system.back:
    description: Permissão para voltar ao local alterior do seu teleporte.
    default: op
  system.bigorna:
    description: Permissão para abrir uma bigorna virtual.
    default: op
  system.chapeu:
    description: Permissão para vestir um chapeu.
    default: op
  system.clear: 
    description: Permissão para limpar o seu inventario.
    default: op
  system.clear.outros: 
    description: Permissão para limpar o inventario de outras pessoas.
    default: op
  system.clearchat:
    description: Permissão para limpar o chat do servidor.
    default: op
  system.compactar:
    description: Permissão para compactar todos os itens do inventario.
    default: op
  system.cores:
    description: Permissão para ver a lista de cores do minecraft.
    default: op
  system.cornabigorna:
    description: Permissão para renomear itens com cores.
    default: op
  system.cornaplaca:
    description: Permissão para renomear itens com cores.
    default: op
  system.craft:
    description: Permissão para abrir uma bancada de trabalho virtual.
    default: op
  system.crashar:
    description: Permissão para crashar o minecraft de um player.
    default: op
  system.criarkit:
    description: Permissão para criar um kit.
    default: op
  system.darkit:
    description: Permissão para enviar um kit.
    default: op
  system.delhome:
    description: Permissão para definir uma home.
    default: op
  system.delkit:
    description: Permissão para deletar um kit.
    default: op
  system.delwarp:
    description: Permissão para deletar uma warp.
    default: op
  system.derreter: 
    description: Permissão para derreter todos os minérios do inventario.
    default: op
  system.divulgar:
    description: Permissão para divulgar um link no chat.
    default: op
  system.echest:
    description: Permissão para abrir o enderchest virtual.
    default: op
  system.echest.mod:
    description: Permissão para ver o enderchest virtual de outras pessoas.
    default: op
  system.echest.admin:
    description: Permissão para editar o enderchest virtual de outras pessoas.
    default: op
  system.editaritem:
    description: Permissão para editar o item que esta segurando na mão.
    default: op
  system.editarkit: 
    description: Permissão para editar um kit criado.
    default: op
  system.editarplaca:
    description: Permissão para editar uma placa usando o comando /editarplaca.
    default: op
  system.enchant: 
    description: Permissão para encantar um item usando /encantar.
    default: op
  system.estatisticas:
    description: Permissão para ver as estatisticas de um player usando /estatisticas.
    default: op
  system.executarsom:
    description: Permissão para enviar um som para um player ou para todo servidor.
    default: op
  system.feed:
    description: Permissão para regenerar sua fome usando o comando /feed.
    default: op
  system.fly:
    description: Permissão para ativar ou desativar o seu modo fly.
    default: op
  system.fly.staff:
    description: Permissão para poder usar o fly em qualquer mundo.
    default: op
  system.fly.outros:
    description: Permissão para ativar ou desativar o fly de outras pessoas.
    default: op
  system.gamemode:
    description: Permissão para poder alterar o seu modo de jogo.
    default: op
  system.gamemode.outros:
    description: Permissão para poder alterar o modo de jogo de outras pessoas.
    default: op
  system.gamemode.survival: 
    description: Permissão para alterar o seu modo de jogo para survival.
    default: op
  system.gamemode.creative: 
    description: Permissão para alterar o seu modo de jogo para criativo.
    default: op
  system.gamemode.adventure: 
    description: Permissão para alterar o seu modo de jogo para aventura.
    default: op
  system.gamemode.spectator: 
    description: Permissão para alterar o seu modo de jogo para espectador.
    default: op
  system.god:
    description: Permissão para ativar ou desativar o seu modo god.
    default: op
  system.god.outros:
    description: Permissão para ativar ou desativar o god de outras pessoas.
    default: op
  system.heal:
    description: Permissão para regenerar sua fome usando o comando /heal.
    default: op
  system.home:
    description: Permissão para se teleportar até uma home.
    default: op
  system.home.admin:
    description: Permissão para ver e para se teleportar para as homes privadas de alguem.
    default: op
  system.invsee: 
    description: Permissão para abrir o inventario de um player.
    default: op
  system.invsee.admin: 
    description: Permissão para editar o inventario de um player.
    default: op
  system.kit:
    description: Permissão para utilizar o comando /kit.
    default: op
  system.kit.all: 
    description: Permissão para poder pegar qualquer kit.
    default: op
  system.kits:
    description: Permissão para ver a lista de kits disponiveis.
    default: op
  system.homes:
    description: Permissão para ver a lista de homes.
    default: op
  system.lixo:
    description: Permissão para abrir a lixeira virtual.
    default: op
  system.lotado.entrar:
    description: Permissão para entrar no servidor mesmo estando lotado.
    default: false
  system.luz:
    description: Permissão para ligar e desligar a lanterna.
    default: op
  system.manterxp:
    description: Permissão para não perder xp ao morrer.
    default: op
  system.mundovip:
    description: Permissão para usar o comando /mundovip.
    default: op
  system.online:
    description: Permissão para ver o número de players online no servidor.
    default: op
  system.particular:
    description: Permissão para definir uma home como particular.
    default: op
  system.ping:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: op
  system.potion: 
    description: Permissão para editar uma poção usando /potion.
    default: op
  system.publica:
    description: Permissão para definir uma home como publica.
    default: op
  system.renderizacao:
    description: Permissão para alterar sua renderização usando o comando /renderizacao.
    default: op
  system.renderizacao.staff:
    description: Permissão para poder usar uma renderização maior que a configurada no bukkit do servidor.
    default: op
  system.reparar:
    description: Permissão para reparar itens usando o comando /reparar.
    default: op
  system.reparar.all:
    description: Permissão para reparar itens usando o comando /reparar.
    default: op
  system.semdelay:
    description: Permissão para se teleportar sem ter que esperar o delay.
    default: op
  system.sethome:
    description: Permissão para definir uma home.
    default: op
  system.setmundovip:
    description: Permissão para definir a area vip e não vip do servidor.
    default: op
  system.setspawn: 
    description: Permissão para definir o spawn do servidor.
    default: op
  system.setwarp:
    description: Permissão para definir uma warp.
    default: op
  system.sgive:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: op
  system.slime:
    description: Permissão para verificar se você esta em uma slimechunk.
    default: op
  system.spawn:
    description: Permissão para se teleportar até o spawn.
    default: op
  system.spawn.vip:
    description: Permissão para nascer direto no spawn vip.
    default: op
  system.speed:
    description: Permissão para alterar a sua velocidade.
    default: op
  system.speed.outros:
    description: Permissão para alterar a sua velocidade de outros players.
    default: op
  system.sudo:
    description: Permissão para executar um comando para outro player.
    default: op
  system.system:
    description: Permissão para usar o comando gerenciador do plugin.
    default: op
  system.terminal:
    description: Permissão para executar um comando no terminal do sistema operacional.
    default: op
  system.title:
    description: Permissão para enviar um title para todo servidor.
    default: op
  system.tp:
    description: Permissão para executar teleportes.
    default: op
  system.tpa:
    description: Permissão para enviar uma solicitação de teleporte.
    default: op
  system.tpaccept:
    description: Permissão para aceitar uma solicitação de teleporte.
    default: op
  system.tpall:
    description: Permissão para teleportar todos os players do servidor.
    default: op
  system.tpcancel:
    description: Permissão para cancelar uma solicitação de teleporte enviada.
    default: op
  system.tpdeny:
    description: Permissão para negar uma solicitação de teleporte.
    default: op
  system.tphere:
    description: Permissão para puxar um player até você.
    default: op
  system.tptoggle:
    description: Permissão para desabilitar o recebimento de solicitações de teleporte.
    default: op
  system.vanish:
    description: Permissão para ativar ou desativar o seu modo vanish.
    default: op
  system.vanish.outros:
    description: Permissão para ativar ou desativar o vanish de outras pessoas.
    default: op
  system.verinfo:
    description: Permissão para ver as informações de um player.
    default: op
  system.verkit:
    description: Permissão para ver os itens de um kit usando /verkit.
    default: op
  system.vip:
    description: Permissão para se teleportar até a area vip.
    default: op
  system.warp:
    description: Permissão para se teleportar para uma warp.
    default: op
  system.warp.all:
    description: Permissão para se teleportar para qualquer warp.
    default: op
  system.warps:
    description: Permissão para ver a lista de warps disponiveis.
    default: op
  system.chat.destaque:
    default: false
  system.bypass.comandobloqueado:
    description: Permissão para usar comandos que foram bloqueados.
    default: false
  system.bypass.containerbloqueado:
    description: Permissão para abrir um inventario que foi bloqueado.
    default: false
  system.bypass.craftbloqueado:
    description: Permissão para craftar itens que foram bloqueados.
    default: false
  system.bypass.delaydivulgar:
    description: Permissão para pegar divulgar esperar o delay.
    default: false
  system.bypass.delaykit:
    description: Permissão para pegar um kit sem precisar esperar o delay.
    default: false
  system.bypass.entraremveiculos:
    description: Permissão para entrar em veiculos mesmo se estiver bloqueado.
    default: false
  system.bypass.entrarnacama:
    description: Permissão para entrar na cama mesmo se ela estiver bloqueada.
    default: false
  system.bypass.placabloqueada:
    description: Permissão para escrever nas placas mesmo se elas estiverem bloqueadas.
    default: false
  system.bypass.shiftemcontainer:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.teleportarporportal:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.usarnametag:
    description: Permissão para usar a NameTag mesmo se ela estiver bloqueada.
    default: false

  system.gamemode.all:
    description: Permissão para poder entrar em todos os modos de jogo.
    default: false
    children:
      system.gamemode.survival: true
      system.gamemode.creative: true
      system.gamemode.adventure: true
      system.gamemode.spectator: true

  system.bypass.all:
    description: Permissão para burlar todos os recursos do plugin.
    default: false
    children:
      system.bypass.comandobloqueado: true
      system.bypass.containerbloqueado: true
      system.bypass.craftbloqueado: true
      system.bypass.delaydivulgar: true
      system.bypass.delaykit: true
      system.bypass.entraremveiculos: true
      system.bypass.entrarnacama: true
      system.bypass.placabloqueada: true
      system.bypass.shiftemcontainer: true
      system.bypass.teleportarporportal: true
      system.bypass.usarnametag: true

  system.admin:
    description: Acesso a todos os recursos do plugin.
    default: op
    children:
      system.alerta: true
      system.back: true
      system.bigorna: true
      system.chapeu: true
      system.clear.outros: true
      system.clear: true
      system.clearchat: true
      system.compactar: true
      system.cores: true
      system.cornabigorna: true
      system.cornaplaca: true
      system.craft: true
      system.crashar: true
      system.criarkit: true
      system.darkit: true
      system.delhome: true
      system.delkit: true
      system.delwarp: true
      system.derreter: true
      system.divulgar: true
      system.echest.admin: true
      system.echest.mod: true
      system.echest: true
      system.editaritem: true
      system.editarkit: true
      system.editarplaca: true
      system.enchant: true
      system.estatisticas: true
      system.executarsom: true
      system.feed: true
      system.fly.outros: true
      system.fly.staff: true
      system.fly: true
      system.gamemode.all: true
      system.gamemode.outros: true
      system.gamemode: true
      system.god.outros: true
      system.god: true
      system.heal: true
      system.home.admin: true
      system.home: true
      system.homes: true
      system.invsee.admin: true
      system.invsee: true
      system.kit.all: true
      system.kit: true
      system.kits: true
      system.lixo: true
      system.lotado.entrar: true
      system.luz: true
      system.manterxp: true
      system.mundovip: true
      system.online: true
      system.particular: true
      system.ping: true
      system.potion: true
      system.publica: true
      system.renderizacao: true
      system.reparar: true
      system.reparar.all: true
      system.semdelay: true
      system.sethome: true
      system.setmundovip: true
      system.setspawn: true
      system.setwarp: true
      system.sgive: true
      system.skull: true
      system.slime: true
      system.spawn: true
      system.spawn.vip: true
      system.speed.outros: true
      system.speed: true
      system.sudo: true
      system.system: true
      system.terminal: true
      system.title: true
      system.tp: true
      system.tpa: true
      system.tpaccept: true
      system.tpall: true
      system.tpcancel: true
      system.tpdeny: true
      system.tphere: true
      system.tptoggle: true
      system.vanish.outros: true
      system.vanish: true
      system.verinfo: true
      system.verkit: true
      system.vip: true
      system.warp: true
      system.warp.all: true
      system.warps: true